services:
  frontend:
    build:
      context: ./frontend
    hostname: frontend
    container_name: battlecards-frontend
    restart: unless-stopped
    volumes:
      - ./frontend:/frontend
    networks:
      - battlecards-net

  backend:
    build:
      context: ./backend
    hostname: backend
    container_name: battlecards-backend
    restart: unless-stopped
    volumes:
      - ./backend:/backend
    networks:
      - battlecards-net
    environment:
      - MONGODB_URI=mongodb://root:password@mongo:27017/communism_battlecards?authSource=admin

  nginx:
    image: nginx:latest
    container_name: battlecards-router
    hostname: nginx
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - battlecards-net
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"

  mongodb:
    image: mongo:latest
    hostname: mongo
    container_name: battlecards-data
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    networks:
      - battlecards-net
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=communism_battlecards

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: battlecards-cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      TUNNEL_TOKEN: ${TUNNEL_TOKEN}
    networks:
      - battlecards-net
    depends_on:
      - nginx

networks:
  battlecards-net:
    driver: bridge

volumes:
  mongo-data:
