services:
  frontend:
    build:
      context: ./frontend
    hostname: frontend
    container_name: battlecards-frontend
    restart: unless-stopped
    volumes:
      - ./frontend:/frontend
    networks:
      - battlecards-net

  backend:
    build:
      context: ./backend
    hostname: backend
    container_name: battlecards-backend
    restart: unless-stopped
    volumes:
      - ./backend:/backend
    networks:
      - battlecards-net
    environment:
      - MONGODB_URI=mongodb+srv://Felix:Felix@cluster0.58kx042.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0

  nginx:
    image: nginx:latest
    container_name: battlecards-router
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - battlecards-net
    depends_on:
      - frontend
      - backend
    ports:
      - "1000:80"

networks:
  battlecards-net:
    driver: bridge